export const GET_MEMBERS_START = 'GITHUB/GET_MEMBERS_START';
export const GET_MEMBERS_SUCCEED = 'GITHUB/GET_MEMBERS_SUCCEED';
export const GET_MEMBERS_FAIL = 'GITHUB/GET_MEMBERS_FAIL';
export const SEARCH_REPOSITORIES_START = 'GITHUB/SEARCH_REPOSITORIES_START';
export const SEARCH_REPOSITORIES_SUCCEED = 'GITHUB/SEARCH_REPOSITORIES_SUCCEED';
export const SEARCH_REPOSITORIES_FAIL = 'GITHUB/SEARCH_REPOSITORIES_FAIL';

export const CALL_START = 'CALL_START';
export const JOIN_ROOM_START = 'JOIN_ROOM_START';
export const WAIT_CALLING_START = 'WAIT_CALLING_START';
export const TAKE_CALLING_START = 'TAKE_CALLING_START';
